Update: Parse argument with getopts

diff --git a/framework/fsbfrm b/framework/fsbfrm
--- a/framework/fsbfrm
+++ b/framework/fsbfrm
@@ -4,8 +4,9 @@ set -euo pipefail
 
 TMPDIR="${TMPDIR:-/tmp}"
 current_dir="$( cd "$( dirname "${0}" )" && pwd )"
-meta_filename="target.json"
+out_dir="$current_dir/out"
 build_target=()
+meta_filename="target.json"
 
 find(){
     if { command find --help 2>/dev/null || true; } | grep -q "GNU" 1>/dev/null; then
@@ -140,8 +141,11 @@ insert_remote(){
         echo "Inserting $key" >&2
         insert_url="$(jq -r ".[\"remote-inserts\"][\"$key\"]" "$target/${meta_filename}")"
         if [[ -n "$insert_url" ]]; then
-            curl -f -L --no-progress-meter  "$insert_url" > "$TMPDIR/remote_insert" || {
-                echo "Failed to get remote insert $insert_url" >&2
+            #readarray -t remote_file < <(curl -s "$insert_url")
+            #print_array "${remote_file[@]}" > 
+            curl -sLf "$insert_url" > "$TMPDIR/remote_insert" || {
+                echo "Failed to download $insert_url" >&2
+                echo "Please check $key in ${target}/${meta_filename}" >&2
                 return 1
             }
             readarray -t base_script< <(print_array "${base_script[@]}" | sed "/^${key}$/r $TMPDIR/remote_insert" | sed "/^${key}$/d")
@@ -170,7 +174,7 @@ call(){
     "$@"
 }
 
-build_make_script(){
+build(){
     local target="$1"
     {
         call get_header "$target"
@@ -178,20 +182,7 @@ build_make_script(){
         call get_func "$target" 
         call make_entrypoint "$target"
         call get_footer "$target"
-    } | insert_remote "$target"
-}
-
-build(){
-    local target="$1" bash_script
-    build_make_script "$target" | {
-        readarray -t bash_script
-        printf '%s\n' "${bash_script[@]}" | shfmt || {
-            echo "Failed to format script" >&2
-            printf '%s\n' "${bash_script[@]}"
-            return 1
-        }
-    }
-    return 0
+    } | insert_remote "$target" | shfmt
 }
 
 get_filename(){
@@ -199,32 +190,51 @@ get_filename(){
     jq -r ".filename" "$target/${meta_filename}"
 }
 
-remove_out(){
-    local target="$1"
-    rm -f "${out_dir}/$(get_filename "${target}")"
-}
 
-out_dir="$current_dir/out"
-mkdir -p "${out_dir}"
 
-if (( $# == 0 )); then
-    readarray -t build_target < <(get_build_target)
-else
+while getopts "C:o:" OPT; do
+  case "$OPT" in
+    C)
+        current_dir="$OPTARG"
+        ;;
+    o)
+        out_dir="$OPTARG"
+        ;;
+    *)
+        echo "Usage: $0 [-C]" >&2
+        exit 1
+        ;;
+  esac
+done
+
+shift "$((OPTIND - 1))"
+
+if (( $# > 0 )); then
     build_target=("$@")
+else
+    readarray -t build_target < <(get_build_target)
 fi
 
-for target in "${build_target[@]}"; do
-    if [[ "$(basename "${target}")" = "$meta_filename" ]]; then
-        target="$(dirname "${target}")"
-    fi
-    if [ ! -e "$target/${meta_filename}" ]; then
-        echo "Target $target not found" >&2
-        continue
-    fi
+echo "Build: ${build_target[*]}" >&2
 
-    #trap 'remove_out "${target}"' EXIT INT TERM HUP
+for target in "${build_target[@]}"; do
+    if [[ "$(basename "$target")" = "$meta_filename" ]]; then
+        if [[ -e "${target}" ]]; then
+            readarray -t build_target < <(printf '%s\n' "${build_target[@]}" | sed "s|^${target}$|$(dirname "${target}")|g")
+        else
+            echo "Target $target is not found" >&2
+            exit 1
+        fi
+    elif ! [[ -e "${target}/${meta_filename}" ]]; then
+        echo "Target ${target}/${meta_filename} is not found" >&2
+        exit 1
+    fi
+done
+
+mkdir -p "${out_dir}"
+
+for target in "${build_target[@]}"; do
     echo "Building $target" >&2
     build "${target}" > "${out_dir}/$(get_filename "${target}")"
     chmod +x "${out_dir}/$(get_filename "${target}")"
-done #< <(get_build_target)
-
+done
